In [1]:
MY_PLAYERS = [
    'Jahmyr Gibbs',
    'David Montgomery',
    'Chris Olave',
    'DeVonta Smith',
    'Jameson Williams',
    'Breece Hall',
    'Kyle Pitts',
    'Denzel Boston',
    'Woody Marks',
    'Alvin Kamara',
    'Travis Kelce',
    'Tank Dell',
    'Zach Charbonnet'
]

In [2]:
MY_PLAYERS

['Jahmyr Gibbs',
 'David Montgomery',
 'Chris Olave',
 'DeVonta Smith',
 'Jameson Williams',
 'Breece Hall',
 'Kyle Pitts',
 'Denzel Boston',
 'Woody Marks',
 'Alvin Kamara',
 'Travis Kelce',
 'Tank Dell',
 'Zach Charbonnet']

In [3]:
import nflreadpy as nfl

for item in dir(nfl):
    print(item)

__all__
__builtins__
__cached__
__doc__
__file__
__loader__
__name__
__package__
__path__
__spec__
__version__
cache
clear_cache
config
downloader
get_current_season
get_current_week
load_combine
load_contracts
load_depth_charts
load_draft_picks
load_ff_opportunity
load_ff_playerids
load_ff_rankings
load_ffverse
load_ftn_charting
load_injuries
load_nextgen_stats
load_officials
load_participation
load_pbp
load_pfr_advstats
load_player_stats
load_players
load_rosters
load_rosters_weekly
load_schedules
load_snap_counts
load_stats
load_team_stats
load_teams
load_trades
utils_date
version

In [4]:
player_stats = nfl.load_player_stats()

print(player_stats.shape)
print(player_stats.columns)

(4449, 150)
['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'week', 'season_type', 'game_id', 'team', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'def_punt_blocks', 'def_pat_blocks', 'def_fg_blocks', 'def_2pt_atts', 'def_2pt_made', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

In [5]:
players = nfl.load_players()

print(players.shape)

(24844, 39)

In [6]:
players.select("display_name").filter(
    players["display_name"].str.contains("Pitts")
)

shape: (10, 1)
┌─────────────────┐
│ display_name    │
│ ---             │
│ str             │
╞═════════════════╡
│ Chester Pitts   │
│ DeRonnie Pitts  │
│ Derrek Pitts    │
│ Frank Pitts     │
│ John Pitts      │
│ Kyle Pitts      │
│ Lafayette Pitts │
│ Mike Pitts      │
│ Ron Pitts       │
│ Thyrick Pitts   │
└─────────────────┘

In [7]:
my_player_info = (
    players
    .filter(
        players["display_name"].is_in(MY_PLAYERS)
        & players["position"].is_in(["RB", "WR", "TE"])
    )
    .select([
        "gsis_id",
        "display_name",
        "position",
        "latest_team"
    ])
)

my_player_info

shape: (13, 4)
┌────────────┬──────────────────┬──────────┬─────────────┐
│ gsis_id    ┆ display_name     ┆ position ┆ latest_team │
│ ---        ┆ ---              ┆ ---      ┆ ---         │
│ str        ┆ str              ┆ str      ┆ str         │
╞════════════╪══════════════════╪══════════╪═════════════╡
│ 00-0041037 ┆ Denzel Boston    ┆ WR       ┆ CLE         │
│ 00-0039165 ┆ Zach Charbonnet  ┆ RB       ┆ SEA         │
│ 00-0038977 ┆ Tank Dell        ┆ WR       ┆ HOU         │
│ 00-0039139 ┆ Jahmyr Gibbs     ┆ RB       ┆ DET         │
│ 00-0038120 ┆ Breece Hall      ┆ RB       ┆ NYJ         │
│ …          ┆ …                ┆ …        ┆ …           │
│ 00-0035685 ┆ David Montgomery ┆ RB       ┆ HOU         │
│ 00-0037239 ┆ Chris Olave      ┆ WR       ┆ NO          │
│ 00-0036970 ┆ Kyle Pitts       ┆ TE       ┆ ATL         │
│ 00-0036912 ┆ DeVonta Smith    ┆ WR       ┆ PHI         │
│ 00-0037240 ┆ Jameson Williams ┆ WR       ┆ DET         │
└────────────┴──────────────────┴──────────┴─────────────┘

In [8]:
schedule = nfl.load_schedules()

print(schedule.shape)

for col in schedule.columns:
    print(col)

(7548, 46)
game_id
season
game_type
week
gameday
weekday
gametime
away_team
away_score
home_team
home_score
location
result
total
overtime
old_game_id
gsis
nfl_detail_id
pfr
pff
espn
ftn
away_rest
home_rest
away_moneyline
home_moneyline
spread_line
away_spread_odds
home_spread_odds
total_line
under_odds
over_odds
div_game
roof
surface
temp
wind
away_qb_id
home_qb_id
away_qb_name
home_qb_name
away_coach
home_coach
referee
stadium_id
stadium

In [9]:
CURRENT_SEASON = nfl.get_current_season()
CURRENT_WEEK = nfl.get_current_week()

print("Season:", CURRENT_SEASON)
print("Week:", CURRENT_WEEK)

week_schedule = (
    schedule.filter(
        (schedule['season'] == CURRENT_SEASON)
        & (schedule['week'] == CURRENT_WEEK)
        & (schedule['game_type'] == 'REG')
    )
    .select([
        'week',
        'gameday',
        'gametime',
        'away_team',
        'home_team'
    ])
)

week_schedule

Season: 2026
Week: 5

shape: (15, 5)
┌──────┬────────────┬──────────┬───────────┬───────────┐
│ week ┆ gameday    ┆ gametime ┆ away_team ┆ home_team │
│ ---  ┆ ---        ┆ ---      ┆ ---       ┆ ---       │
│ i32  ┆ str        ┆ str      ┆ str       ┆ str       │
╞══════╪════════════╪══════════╪═══════════╪═══════════╡
│ 5    ┆ 2026-10-08 ┆ 20:15    ┆ TB        ┆ DAL       │
│ 5    ┆ 2026-10-11 ┆ 09:30    ┆ PHI       ┆ JAX       │
│ 5    ┆ 2026-10-11 ┆ 13:00    ┆ CHI       ┆ GB        │
│ 5    ┆ 2026-10-11 ┆ 13:00    ┆ CIN       ┆ MIA       │
│ 5    ┆ 2026-10-11 ┆ 13:00    ┆ LV        ┆ NE        │
│ …    ┆ …          ┆ …        ┆ …         ┆ …         │
│ 5    ┆ 2026-10-11 ┆ 16:05    ┆ DEN       ┆ LAC       │
│ 5    ┆ 2026-10-11 ┆ 16:25    ┆ DET       ┆ ARI       │
│ 5    ┆ 2026-10-11 ┆ 16:25    ┆ SF        ┆ SEA       │
│ 5    ┆ 2026-10-11 ┆ 20:20    ┆ BAL       ┆ ATL       │
│ 5    ┆ 2026-10-12 ┆ 20:15    ┆ BUF       ┆ LA        │
└──────┴────────────┴──────────┴───────────┴───────────┘

In [10]:
team_stats = nfl.load_team_stats()

print(team_stats.shape)

for col in team_stats.columns:
    print(col)

(128, 138)
season
week
team
season_type
game_id
opponent_team
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
timeouts
fumbles_forced_by_opp
fumbles_not_forced
fumbles_out_of_bounds
fumbles_total
fumbles_lost_total
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance
pt_att
pt_blocked
pt_long
pt_yards
pt_inside_20
pt_out_of_bounds
pt_downed
pt_touchback
pt_fair_caught
pt_returned
pt_return_yards
pt_return_tds
pt_net_yards

In [11]:
print(
    team_stats
    .select("week")
    .unique()
    .sort("week")
)

shape: (4, 1)
┌──────┐
│ week │
│ ---  │
│ i32  │
╞══════╡
│ 1    │
│ 2    │
│ 3    │
│ 4    │
└──────┘

In [12]:
import polars as pl

In [13]:
away_rows = week_schedule.select([
    pl.col("away_team").alias("team"),
    pl.col("home_team").alias("opponent"),
    pl.lit("A").alias("home_away"),
    "gameday",
    "gametime"
])

home_rows = week_schedule.select([
    pl.col("home_team").alias("team"),
    pl.col("away_team").alias("opponent"),
    pl.lit("H").alias("home_away"),
    "gameday",
    "gametime"
])

team_matchups = pl.concat([away_rows, home_rows])

team_matchups

shape: (30, 5)
┌──────┬──────────┬───────────┬────────────┬──────────┐
│ team ┆ opponent ┆ home_away ┆ gameday    ┆ gametime │
│ ---  ┆ ---      ┆ ---       ┆ ---        ┆ ---      │
│ str  ┆ str      ┆ str       ┆ str        ┆ str      │
╞══════╪══════════╪═══════════╪════════════╪══════════╡
│ TB   ┆ DAL      ┆ A         ┆ 2026-10-08 ┆ 20:15    │
│ PHI  ┆ JAX      ┆ A         ┆ 2026-10-11 ┆ 09:30    │
│ CHI  ┆ GB       ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│ CIN  ┆ MIA      ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│ LV   ┆ NE       ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│ …    ┆ …        ┆ …         ┆ …          ┆ …        │
│ LAC  ┆ DEN      ┆ H         ┆ 2026-10-11 ┆ 16:05    │
│ ARI  ┆ DET      ┆ H         ┆ 2026-10-11 ┆ 16:25    │
│ SEA  ┆ SF       ┆ H         ┆ 2026-10-11 ┆ 16:25    │
│ ATL  ┆ BAL      ┆ H         ┆ 2026-10-11 ┆ 20:20    │
│ LA   ┆ BUF      ┆ H         ┆ 2026-10-12 ┆ 20:15    │
└──────┴──────────┴───────────┴────────────┴──────────┘

In [14]:
my_roster_matchups = (
    my_player_info
    .join(
        team_matchups,
        left_on="latest_team",
        right_on="team",
        how="left"
    )
)

my_roster_matchups

shape: (13, 8)
┌────────────┬─────────────┬──────────┬─────────────┬──────────┬───────────┬────────────┬──────────┐
│ gsis_id    ┆ display_nam ┆ position ┆ latest_team ┆ opponent ┆ home_away ┆ gameday    ┆ gametime │
│ ---        ┆ e           ┆ ---      ┆ ---         ┆ ---      ┆ ---       ┆ ---        ┆ ---      │
│ str        ┆ ---         ┆ str      ┆ str         ┆ str      ┆ str       ┆ str        ┆ str      │
│            ┆ str         ┆          ┆             ┆          ┆           ┆            ┆          │
╞════════════╪═════════════╪══════════╪═════════════╪══════════╪═══════════╪════════════╪══════════╡
│ 00-0041037 ┆ Denzel      ┆ WR       ┆ CLE         ┆ NYJ      ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│            ┆ Boston      ┆          ┆             ┆          ┆           ┆            ┆          │
│ 00-0039165 ┆ Zach        ┆ RB       ┆ SEA         ┆ SF       ┆ H         ┆ 2026-10-11 ┆ 16:25    │
│            ┆ Charbonnet  ┆          ┆             ┆          ┆           ┆            ┆          │
│ 00-0038977 ┆ Tank Dell   ┆ WR       ┆ HOU         ┆ TEN      ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│ 00-0039139 ┆ Jahmyr      ┆ RB       ┆ DET         ┆ ARI      ┆ A         ┆ 2026-10-11 ┆ 16:25    │
│            ┆ Gibbs       ┆          ┆             ┆          ┆           ┆            ┆          │
│ 00-0038120 ┆ Breece Hall ┆ RB       ┆ NYJ         ┆ CLE      ┆ H         ┆ 2026-10-11 ┆ 13:00    │
│ …          ┆ …           ┆ …        ┆ …           ┆ …        ┆ …         ┆ …          ┆ …        │
│ 00-0035685 ┆ David       ┆ RB       ┆ HOU         ┆ TEN      ┆ A         ┆ 2026-10-11 ┆ 13:00    │
│            ┆ Montgomery  ┆          ┆             ┆          ┆           ┆            ┆          │
│ 00-0037239 ┆ Chris Olave ┆ WR       ┆ NO          ┆ MIN      ┆ H         ┆ 2026-10-11 ┆ 13:00    │
│ 00-0036970 ┆ Kyle Pitts  ┆ TE       ┆ ATL         ┆ BAL      ┆ H         ┆ 2026-10-11 ┆ 20:20    │
│ 00-0036912 ┆ DeVonta     ┆ WR       ┆ PHI         ┆ JAX      ┆ A         ┆ 2026-10-11 ┆ 09:30    │
│            ┆ Smith       ┆          ┆             ┆          ┆           ┆            ┆          │
│ 00-0037240 ┆ Jameson     ┆ WR       ┆ DET         ┆ ARI      ┆ A         ┆ 2026-10-11 ┆ 16:25    │
│            ┆ Williams    ┆          ┆             ┆          ┆           ┆            ┆          │
└────────────┴─────────────┴──────────┴─────────────┴──────────┴───────────┴────────────┴──────────┘

In [15]:
defense_check = (
    team_stats
    .filter(
        (team_stats["season"] == CURRENT_SEASON)
        & (team_stats["season_type"] == "REG")
        & (team_stats["week"] < CURRENT_WEEK)
    )
    .select([
        "week",
        "team",
        "opponent_team",
        "passing_yards",
        "passing_tds",
        "rushing_yards",
        "rushing_tds",
        "attempts",
        "carries",
        "sacks_suffered",
        "sack_yards_lost"
    ])
)

defense_check

shape: (128, 11)
┌──────┬──────┬──────────────┬──────────────┬───┬──────────┬─────────┬──────────────┬──────────────┐
│ week ┆ team ┆ opponent_tea ┆ passing_yard ┆ … ┆ attempts ┆ carries ┆ sacks_suffer ┆ sack_yards_l │
│ ---  ┆ ---  ┆ m            ┆ s            ┆   ┆ ---      ┆ ---     ┆ ed           ┆ ost          │
│ i32  ┆ str  ┆ ---          ┆ ---          ┆   ┆ i32      ┆ i32     ┆ ---          ┆ ---          │
│      ┆      ┆ str          ┆ i32          ┆   ┆          ┆         ┆ i32          ┆ i32          │
╞══════╪══════╪══════════════╪══════════════╪═══╪══════════╪═════════╪══════════════╪══════════════╡
│ 1    ┆ ARI  ┆ LAC          ┆ 277          ┆ … ┆ 37       ┆ 34      ┆ 1            ┆ 0            │
│ 1    ┆ ATL  ┆ PIT          ┆ 143          ┆ … ┆ 22       ┆ 31      ┆ 4            ┆ -25          │
│ 1    ┆ BAL  ┆ IND          ┆ 324          ┆ … ┆ 25       ┆ 37      ┆ 2            ┆ -20          │
│ 1    ┆ BUF  ┆ HOU          ┆ 334          ┆ … ┆ 29       ┆ 21      ┆ 2            ┆ -11          │
│ 1    ┆ CAR  ┆ CHI          ┆ 361          ┆ … ┆ 38       ┆ 22      ┆ 2            ┆ -8           │
│ …    ┆ …    ┆ …            ┆ …            ┆ … ┆ …        ┆ …       ┆ …            ┆ …            │
│ 4    ┆ SEA  ┆ LAC          ┆ 168          ┆ … ┆ 22       ┆ 33      ┆ 3            ┆ -20          │
│ 4    ┆ SF   ┆ DEN          ┆ 218          ┆ … ┆ 30       ┆ 35      ┆ 0            ┆ 0            │
│ 4    ┆ TB   ┆ GB           ┆ 148          ┆ … ┆ 27       ┆ 31      ┆ 3            ┆ -14          │
│ 4    ┆ TEN  ┆ BAL          ┆ 222          ┆ … ┆ 31       ┆ 26      ┆ 1            ┆ -10          │
│ 4    ┆ WAS  ┆ IND          ┆ 232          ┆ … ┆ 37       ┆ 22      ┆ 2            ┆ -15          │
└──────┴──────┴──────────────┴──────────────┴───┴──────────┴─────────┴──────────────┴──────────────┘

DEFENSE

In [16]:
defense_efficiency = (
    defense_check
    .group_by("opponent_team")
    .agg([
        pl.col("rushing_yards").sum().alias("rush_yards_allowed_total"),
        pl.col("carries").sum().alias("rush_attempts_faced"),

        pl.col("passing_yards").sum().alias("pass_yards_allowed_total"),
        pl.col("sack_yards_lost").sum().alias("sack_yards_lost_total"),
        pl.col("attempts").sum().alias("pass_attempts_faced"),
        pl.col("sacks_suffered").sum().alias("sacks_faced"),

        pl.col("rushing_yards").sum().alias("total_rush_yards"),
        pl.col("passing_yards").sum().alias("total_pass_yards")
    ])
    .with_columns([
        (
            pl.col("rush_yards_allowed_total")
            / pl.col("rush_attempts_faced")
        ).alias("rush_ypc_allowed"),

        (
            (
                pl.col("pass_yards_allowed_total")
                - pl.col("sack_yards_lost_total")
            )
            /
            (
                pl.col("pass_attempts_faced")
                + pl.col("sacks_faced")
            )
        ).alias("net_pass_yds_per_dropback"),

        (
            (
                pl.col("total_pass_yards")
                - pl.col("sack_yards_lost_total")
                + pl.col("total_rush_yards")
            )
            /
            (
                pl.col("pass_attempts_faced")
                + pl.col("sacks_faced")
                + pl.col("rush_attempts_faced")
            )
        ).alias("yards_per_play_allowed")
    ])
    .rename({
        "opponent_team": "defense_team"
    })
    .select([
        "defense_team",
        "rush_ypc_allowed",
        "net_pass_yds_per_dropback",
        "yards_per_play_allowed"
    ])
    .with_columns([
        pl.col("rush_ypc_allowed").round(2),
        pl.col("net_pass_yds_per_dropback").round(2),
        pl.col("yards_per_play_allowed").round(2)
    ])
)

defense_efficiency

shape: (32, 4)
┌──────────────┬──────────────────┬───────────────────────────┬────────────────────────┐
│ defense_team ┆ rush_ypc_allowed ┆ net_pass_yds_per_dropback ┆ yards_per_play_allowed │
│ ---          ┆ ---              ┆ ---                       ┆ ---                    │
│ str          ┆ f64              ┆ f64                       ┆ f64                    │
╞══════════════╪══════════════════╪═══════════════════════════╪════════════════════════╡
│ NYG          ┆ 4.69             ┆ 6.31                      ┆ 5.66                   │
│ NO           ┆ 5.05             ┆ 7.44                      ┆ 6.31                   │
│ NYJ          ┆ 4.26             ┆ 6.4                       ┆ 5.42                   │
│ BAL          ┆ 3.88             ┆ 6.79                      ┆ 5.57                   │
│ BUF          ┆ 4.03             ┆ 7.43                      ┆ 6.0                    │
│ …            ┆ …                ┆ …                         ┆ …                      │
│ SF           ┆ 3.73             ┆ 5.84                      ┆ 4.97                   │
│ PIT          ┆ 4.34             ┆ 7.77                      ┆ 6.21                   │
│ PHI          ┆ 4.03             ┆ 6.53                      ┆ 5.39                   │
│ ATL          ┆ 2.72             ┆ 6.23                      ┆ 5.26                   │
│ CHI          ┆ 4.94             ┆ 7.64                      ┆ 6.47                   │
└──────────────┴──────────────────┴───────────────────────────┴────────────────────────┘

In [17]:
defense_efficiency_check = (
    defense_check
    .with_columns([
        (
            pl.col("rushing_yards") / pl.col("carries")
        ).alias("rush_ypc_allowed"),

        (
            (pl.col("passing_yards") - pl.col("sack_yards_lost"))
            /
            (pl.col("attempts") + pl.col("sacks_suffered"))
        ).alias("net_pass_ypd_allowed"),

        (
            (
                pl.col("passing_yards")
                - pl.col("sack_yards_lost")
                + pl.col("rushing_yards")
            )
            /
            (
                pl.col("attempts")
                + pl.col("sacks_suffered")
                + pl.col("carries")
            )
        ).alias("yards_per_play_allowed")
    ])
)

defense_efficiency_check.select([
    "week",
    "team",
    "opponent_team",
    "rush_ypc_allowed",
    "net_pass_ypd_allowed",
    "yards_per_play_allowed"
])

shape: (128, 6)
┌──────┬──────┬───────────────┬──────────────────┬──────────────────────┬────────────────────────┐
│ week ┆ team ┆ opponent_team ┆ rush_ypc_allowed ┆ net_pass_ypd_allowed ┆ yards_per_play_allowed │
│ ---  ┆ ---  ┆ ---           ┆ ---              ┆ ---                  ┆ ---                    │
│ i32  ┆ str  ┆ str           ┆ f64              ┆ f64                  ┆ f64                    │
╞══════╪══════╪═══════════════╪══════════════════╪══════════════════════╪════════════════════════╡
│ 1    ┆ ARI  ┆ LAC           ┆ 3.411765         ┆ 7.289474             ┆ 5.458333               │
│ 1    ┆ ATL  ┆ PIT           ┆ 3.870968         ┆ 6.461538             ┆ 5.052632               │
│ 1    ┆ BAL  ┆ IND           ┆ 5.459459         ┆ 12.740741            ┆ 8.53125                │
│ 1    ┆ BUF  ┆ HOU           ┆ 4.095238         ┆ 11.129032            ┆ 8.288462               │
│ 1    ┆ CAR  ┆ CHI           ┆ 5.681818         ┆ 9.225                ┆ 7.967742               │
│ …    ┆ …    ┆ …             ┆ …                ┆ …                    ┆ …                      │
│ 4    ┆ SEA  ┆ LAC           ┆ 4.181818         ┆ 7.52                 ┆ 5.62069                │
│ 4    ┆ SF   ┆ DEN           ┆ 4.0              ┆ 7.266667             ┆ 5.507692               │
│ 4    ┆ TB   ┆ GB            ┆ 4.548387         ┆ 5.4                  ┆ 4.967213               │
│ 4    ┆ TEN  ┆ BAL           ┆ 3.269231         ┆ 7.25                 ┆ 5.465517               │
│ 4    ┆ WAS  ┆ IND           ┆ 4.545455         ┆ 6.333333             ┆ 5.688525               │
└──────┴──────┴───────────────┴──────────────────┴──────────────────────┴────────────────────────┘

In [18]:
defense_stats = (
    defense_check
    .group_by("opponent_team")
    .agg([
        pl.col("passing_yards")
            .mean()
            .alias("pass_yards_allowed"),

        pl.col("passing_tds")
            .sum()
            .alias("pass_tds_allowed"),

        pl.col("rushing_yards")
            .mean()
            .alias("rush_yards_allowed"),

        pl.col("rushing_tds")
            .sum()
            .alias("rush_tds_allowed")
    ])
    .rename({
        "opponent_team": "defense_team"
    })
)

defense_stats

shape: (32, 5)
┌──────────────┬────────────────────┬──────────────────┬────────────────────┬──────────────────┐
│ defense_team ┆ pass_yards_allowed ┆ pass_tds_allowed ┆ rush_yards_allowed ┆ rush_tds_allowed │
│ ---          ┆ ---                ┆ ---              ┆ ---                ┆ ---              │
│ str          ┆ f64                ┆ i32              ┆ f64                ┆ i32              │
╞══════════════╪════════════════════╪══════════════════╪════════════════════╪══════════════════╡
│ NO           ┆ 228.0              ┆ 7                ┆ 147.75             ┆ 9                │
│ GB           ┆ 200.5              ┆ 6                ┆ 139.25             ┆ 7                │
│ ARI          ┆ 247.75             ┆ 11               ┆ 117.5              ┆ 3                │
│ NYG          ┆ 212.25             ┆ 9                ┆ 109.0              ┆ 2                │
│ SEA          ┆ 161.25             ┆ 6                ┆ 102.0              ┆ 1                │
│ …            ┆ …                  ┆ …                ┆ …                  ┆ …                │
│ CIN          ┆ 272.0              ┆ 4                ┆ 99.5               ┆ 3                │
│ IND          ┆ 276.25             ┆ 6                ┆ 131.0              ┆ 5                │
│ CAR          ┆ 242.5              ┆ 5                ┆ 156.5              ┆ 7                │
│ ATL          ┆ 276.5              ┆ 7                ┆ 48.25              ┆ 2                │
│ CLE          ┆ 254.25             ┆ 9                ┆ 113.25             ┆ 0                │
└──────────────┴────────────────────┴──────────────────┴────────────────────┴──────────────────┘

In [19]:
final_board = (
    my_roster_matchups
    .join(
        defense_stats,
        left_on="opponent",
        right_on="defense_team",
        how="left"
    )
)

final_board

shape: (13, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gsis_id   ┆ display_n ┆ position ┆ latest_te ┆ … ┆ pass_yard ┆ pass_tds_ ┆ rush_yard ┆ rush_tds_ │
│ ---       ┆ ame       ┆ ---      ┆ am        ┆   ┆ s_allowed ┆ allowed   ┆ s_allowed ┆ allowed   │
│ str       ┆ ---       ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆          ┆ str       ┆   ┆ f64       ┆ i32       ┆ f64       ┆ i32       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-004103 ┆ Denzel    ┆ WR       ┆ CLE       ┆ … ┆ 205.5     ┆ 5         ┆ 123.5     ┆ 4         │
│ 7         ┆ Boston    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003916 ┆ Zach Char ┆ RB       ┆ SEA       ┆ … ┆ 214.75    ┆ 4         ┆ 99.75     ┆ 2         │
│ 5         ┆ bonnet    ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003897 ┆ Tank Dell ┆ WR       ┆ HOU       ┆ … ┆ 220.5     ┆ 4         ┆ 122.75    ┆ 4         │
│ 7         ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003913 ┆ Jahmyr    ┆ RB       ┆ DET       ┆ … ┆ 247.75    ┆ 11        ┆ 117.5     ┆ 3         │
│ 9         ┆ Gibbs     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003812 ┆ Breece    ┆ RB       ┆ NYJ       ┆ … ┆ 254.25    ┆ 9         ┆ 113.25    ┆ 0         │
│ 0         ┆ Hall      ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003568 ┆ David Mon ┆ RB       ┆ HOU       ┆ … ┆ 220.5     ┆ 4         ┆ 122.75    ┆ 4         │
│ 5         ┆ tgomery   ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003723 ┆ Chris     ┆ WR       ┆ NO        ┆ … ┆ 220.25    ┆ 3         ┆ 94.5      ┆ 1         │
│ 9         ┆ Olave     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003697 ┆ Kyle      ┆ TE       ┆ ATL       ┆ … ┆ 229.0     ┆ 4         ┆ 100.0     ┆ 6         │
│ 0         ┆ Pitts     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003691 ┆ DeVonta   ┆ WR       ┆ PHI       ┆ … ┆ 291.5     ┆ 3         ┆ 74.25     ┆ 2         │
│ 2         ┆ Smith     ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ 00-003724 ┆ Jameson   ┆ WR       ┆ DET       ┆ … ┆ 247.75    ┆ 11        ┆ 117.5     ┆ 3         │
│ 0         ┆ Williams  ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [20]:
final_board = final_board.rename({
    "display_name": "player",
    "latest_team": "team",
    "home_away": "h_a"
})

In [21]:
final_board

shape: (13, 12)
┌────────────┬────────────┬──────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ gsis_id    ┆ player     ┆ position ┆ team ┆ … ┆ pass_yards ┆ pass_tds_a ┆ rush_yards ┆ rush_tds_ │
│ ---        ┆ ---        ┆ ---      ┆ ---  ┆   ┆ _allowed   ┆ llowed     ┆ _allowed   ┆ allowed   │
│ str        ┆ str        ┆ str      ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│            ┆            ┆          ┆      ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32       │
╞════════════╪════════════╪══════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 00-0041037 ┆ Denzel     ┆ WR       ┆ CLE  ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4         │
│            ┆ Boston     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0039165 ┆ Zach       ┆ RB       ┆ SEA  ┆ … ┆ 214.75     ┆ 4          ┆ 99.75      ┆ 2         │
│            ┆ Charbonnet ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038977 ┆ Tank Dell  ┆ WR       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│ 00-0039139 ┆ Jahmyr     ┆ RB       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Gibbs      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038120 ┆ Breece     ┆ RB       ┆ NYJ  ┆ … ┆ 254.25     ┆ 9          ┆ 113.25     ┆ 0         │
│            ┆ Hall       ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 00-0035685 ┆ David      ┆ RB       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│            ┆ Montgomery ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037239 ┆ Chris      ┆ WR       ┆ NO   ┆ … ┆ 220.25     ┆ 3          ┆ 94.5       ┆ 1         │
│            ┆ Olave      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0036970 ┆ Kyle Pitts ┆ TE       ┆ ATL  ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6         │
│ 00-0036912 ┆ DeVonta    ┆ WR       ┆ PHI  ┆ … ┆ 291.5      ┆ 3          ┆ 74.25      ┆ 2         │
│            ┆ Smith      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037240 ┆ Jameson    ┆ WR       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Williams   ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [22]:
keywords = [
    "player",
    "position",
    "week",
    "team",
    "target",
    "reception",
    "receiving",
    "carry",
    "rush",
    "touchdown"
]

for col in player_stats.columns:
    if any(word in col.lower() for word in keywords):
        print(col)

player_id
player_name
player_display_name
position
position_group
week
team
opponent_team
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
target_share
special_teams_tds

In [23]:
for col in player_stats.columns:
    if "carry" in col.lower() or "attempt" in col.lower():
        print(col)

attempts

In [24]:
player_stats.filter(
    player_stats["player_display_name"].is_in([
        "Jahmyr Gibbs",
        "DeVonta Smith",
        "Dalton Schultz"
    ])
).select([
    "player_display_name",
    "position",
    "week",
    "attempts",
    "rushing_yards",
    "targets",
    "receptions"
])

shape: (11, 7)
┌─────────────────────┬──────────┬──────┬──────────┬───────────────┬─────────┬────────────┐
│ player_display_name ┆ position ┆ week ┆ attempts ┆ rushing_yards ┆ targets ┆ receptions │
│ ---                 ┆ ---      ┆ ---  ┆ ---      ┆ ---           ┆ ---     ┆ ---        │
│ str                 ┆ str      ┆ i32  ┆ i32      ┆ i32           ┆ i32     ┆ i32        │
╞═════════════════════╪══════════╪══════╪══════════╪═══════════════╪═════════╪════════════╡
│ Dalton Schultz      ┆ TE       ┆ 1    ┆ 0        ┆ 0             ┆ 8       ┆ 4          │
│ DeVonta Smith       ┆ WR       ┆ 1    ┆ 0        ┆ 0             ┆ 6       ┆ 3          │
│ Jahmyr Gibbs        ┆ RB       ┆ 1    ┆ 0        ┆ 156           ┆ 5       ┆ 5          │
│ Dalton Schultz      ┆ TE       ┆ 2    ┆ 0        ┆ 0             ┆ 14      ┆ 12         │
│ DeVonta Smith       ┆ WR       ┆ 2    ┆ 0        ┆ 0             ┆ 13      ┆ 10         │
│ …                   ┆ …        ┆ …    ┆ …        ┆ …             ┆ …       ┆ …          │
│ Dalton Schultz      ┆ TE       ┆ 3    ┆ 0        ┆ 0             ┆ 3       ┆ 3          │
│ DeVonta Smith       ┆ WR       ┆ 3    ┆ 0        ┆ 0             ┆ 8       ┆ 6          │
│ Jahmyr Gibbs        ┆ RB       ┆ 3    ┆ 0        ┆ 99            ┆ 8       ┆ 7          │
│ Dalton Schultz      ┆ TE       ┆ 4    ┆ 0        ┆ 0             ┆ 2       ┆ 2          │
│ Jahmyr Gibbs        ┆ RB       ┆ 4    ┆ 0        ┆ 46            ┆ 7       ┆ 4          │
└─────────────────────┴──────────┴──────┴──────────┴───────────────┴─────────┴────────────┘

In [25]:
for col in player_stats.columns:
    if "rush" in col.lower():
        print(col)

rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40

In [26]:
player_baseline = (
    player_stats
    .filter(
        player_stats["player_display_name"].is_in(MY_PLAYERS)
        & (player_stats["week"] < CURRENT_WEEK)
        & player_stats["position"].is_in(["RB", "WR", "TE"])
    )
    .select([
        "player_id",
        "player_display_name",
        "position",
        "week",
        "team",
        "rushing_yards",
        "rushing_tds",
        "targets",
        "receptions",
        "receiving_yards",
        "receiving_tds"
    ])
)

player_baseline

shape: (41, 11)
┌────────────┬─────────────┬──────────┬──────┬───┬─────────┬────────────┬─────────────┬────────────┐
│ player_id  ┆ player_disp ┆ position ┆ week ┆ … ┆ targets ┆ receptions ┆ receiving_y ┆ receiving_ │
│ ---        ┆ lay_name    ┆ ---      ┆ ---  ┆   ┆ ---     ┆ ---        ┆ ards        ┆ tds        │
│ str        ┆ ---         ┆ str      ┆ i32  ┆   ┆ i32     ┆ i32        ┆ ---         ┆ ---        │
│            ┆ str         ┆          ┆      ┆   ┆         ┆            ┆ i32         ┆ i32        │
╞════════════╪═════════════╪══════════╪══════╪═══╪═════════╪════════════╪═════════════╪════════════╡
│ 00-0030506 ┆ Travis      ┆ TE       ┆ 1    ┆ … ┆ 5       ┆ 3          ┆ 71          ┆ 0          │
│            ┆ Kelce       ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
│ 00-0035685 ┆ David       ┆ RB       ┆ 1    ┆ … ┆ 3       ┆ 3          ┆ 19          ┆ 1          │
│            ┆ Montgomery  ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
│ 00-0036912 ┆ DeVonta     ┆ WR       ┆ 1    ┆ … ┆ 6       ┆ 3          ┆ 53          ┆ 0          │
│            ┆ Smith       ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
│ 00-0036970 ┆ Kyle Pitts  ┆ TE       ┆ 1    ┆ … ┆ 1       ┆ 0          ┆ 0           ┆ 0          │
│ 00-0037239 ┆ Chris Olave ┆ WR       ┆ 1    ┆ … ┆ 13      ┆ 10         ┆ 182         ┆ 0          │
│ …          ┆ …           ┆ …        ┆ …    ┆ … ┆ …       ┆ …          ┆ …           ┆ …          │
│ 00-0037239 ┆ Chris Olave ┆ WR       ┆ 4    ┆ … ┆ 12      ┆ 8          ┆ 116         ┆ 0          │
│ 00-0037240 ┆ Jameson     ┆ WR       ┆ 4    ┆ … ┆ 8       ┆ 6          ┆ 102         ┆ 0          │
│            ┆ Williams    ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
│ 00-0039139 ┆ Jahmyr      ┆ RB       ┆ 4    ┆ … ┆ 7       ┆ 4          ┆ 31          ┆ 0          │
│            ┆ Gibbs       ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
│ 00-0040583 ┆ Woody Marks ┆ RB       ┆ 4    ┆ … ┆ 1       ┆ 0          ┆ 0           ┆ 0          │
│ 00-0041037 ┆ Denzel      ┆ WR       ┆ 4    ┆ … ┆ 7       ┆ 4          ┆ 89          ┆ 0          │
│            ┆ Boston      ┆          ┆      ┆   ┆         ┆            ┆             ┆            │
└────────────┴─────────────┴──────────┴──────┴───┴─────────┴────────────┴─────────────┴────────────┘

In [27]:
player_summary = (
    player_baseline
    .group_by([
        "player_id",
        "player_display_name",
        "position",
        "team"
    ])
    .agg([
        pl.len().alias("games_played"),

        pl.col("targets").mean().alias("targets_per_game"),
        pl.col("receptions").mean().alias("receptions_per_game"),
        pl.col("receiving_yards").mean().alias("receiving_yards_per_game"),

        pl.col("rushing_yards").mean().alias("rushing_yards_per_game"),

        pl.col("rushing_tds").sum().alias("rushing_tds"),
        pl.col("receiving_tds").sum().alias("receiving_tds")
    ])
)

player_summary

shape: (11, 11)
┌────────────┬────────────┬──────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ player_id  ┆ player_dis ┆ position ┆ team ┆ … ┆ receiving_ ┆ rushing_ya ┆ rushing_td ┆ receiving │
│ ---        ┆ play_name  ┆ ---      ┆ ---  ┆   ┆ yards_per_ ┆ rds_per_ga ┆ s          ┆ _tds      │
│ str        ┆ ---        ┆ str      ┆ str  ┆   ┆ game       ┆ me         ┆ ---        ┆ ---       │
│            ┆ str        ┆          ┆      ┆   ┆ ---        ┆ ---        ┆ i32        ┆ i32       │
│            ┆            ┆          ┆      ┆   ┆ f64        ┆ f64        ┆            ┆           │
╞════════════╪════════════╪══════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 00-0041037 ┆ Denzel     ┆ WR       ┆ CLE  ┆ … ┆ 71.0       ┆ 0.0        ┆ 0          ┆ 2         │
│            ┆ Boston     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037240 ┆ Jameson    ┆ WR       ┆ DET  ┆ … ┆ 57.25      ┆ 0.0        ┆ 0          ┆ 0         │
│            ┆ Williams   ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0033906 ┆ Alvin      ┆ RB       ┆ NO   ┆ … ┆ 15.666667  ┆ 24.666667  ┆ 2          ┆ 0         │
│            ┆ Kamara     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038120 ┆ Breece     ┆ RB       ┆ NYJ  ┆ … ┆ 34.0       ┆ 54.333333  ┆ 1          ┆ 0         │
│            ┆ Hall       ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0030506 ┆ Travis     ┆ TE       ┆ KC   ┆ … ┆ 61.5       ┆ 0.0        ┆ 0          ┆ 2         │
│            ┆ Kelce      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 00-0035685 ┆ David      ┆ RB       ┆ HOU  ┆ … ┆ 16.75      ┆ 31.75      ┆ 2          ┆ 1         │
│            ┆ Montgomery ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0039139 ┆ Jahmyr     ┆ RB       ┆ DET  ┆ … ┆ 46.75      ┆ 88.25      ┆ 5          ┆ 2         │
│            ┆ Gibbs      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0036970 ┆ Kyle Pitts ┆ TE       ┆ ATL  ┆ … ┆ 16.75      ┆ 0.0        ┆ 0          ┆ 0         │
│ 00-0040583 ┆ Woody      ┆ RB       ┆ HOU  ┆ … ┆ 7.75       ┆ 21.75      ┆ 2          ┆ 0         │
│            ┆ Marks      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037239 ┆ Chris      ┆ WR       ┆ NO   ┆ … ┆ 122.75     ┆ 0.0        ┆ 0          ┆ 1         │
│            ┆ Olave      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [28]:
final_board = (
    final_board
    .join(
        player_summary,
        left_on="gsis_id",
        right_on="player_id",
        how="left"
    )
)

final_board

shape: (13, 22)
┌────────────┬────────────┬──────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ gsis_id    ┆ player     ┆ position ┆ team ┆ … ┆ receiving_ ┆ rushing_ya ┆ rushing_td ┆ receiving │
│ ---        ┆ ---        ┆ ---      ┆ ---  ┆   ┆ yards_per_ ┆ rds_per_ga ┆ s          ┆ _tds      │
│ str        ┆ str        ┆ str      ┆ str  ┆   ┆ game       ┆ me         ┆ ---        ┆ ---       │
│            ┆            ┆          ┆      ┆   ┆ ---        ┆ ---        ┆ i32        ┆ i32       │
│            ┆            ┆          ┆      ┆   ┆ f64        ┆ f64        ┆            ┆           │
╞════════════╪════════════╪══════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 00-0041037 ┆ Denzel     ┆ WR       ┆ CLE  ┆ … ┆ 71.0       ┆ 0.0        ┆ 0          ┆ 2         │
│            ┆ Boston     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0039165 ┆ Zach       ┆ RB       ┆ SEA  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│            ┆ Charbonnet ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038977 ┆ Tank Dell  ┆ WR       ┆ HOU  ┆ … ┆ null       ┆ null       ┆ null       ┆ null      │
│ 00-0039139 ┆ Jahmyr     ┆ RB       ┆ DET  ┆ … ┆ 46.75      ┆ 88.25      ┆ 5          ┆ 2         │
│            ┆ Gibbs      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038120 ┆ Breece     ┆ RB       ┆ NYJ  ┆ … ┆ 34.0       ┆ 54.333333  ┆ 1          ┆ 0         │
│            ┆ Hall       ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 00-0035685 ┆ David      ┆ RB       ┆ HOU  ┆ … ┆ 16.75      ┆ 31.75      ┆ 2          ┆ 1         │
│            ┆ Montgomery ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037239 ┆ Chris      ┆ WR       ┆ NO   ┆ … ┆ 122.75     ┆ 0.0        ┆ 0          ┆ 1         │
│            ┆ Olave      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0036970 ┆ Kyle Pitts ┆ TE       ┆ ATL  ┆ … ┆ 16.75      ┆ 0.0        ┆ 0          ┆ 0         │
│ 00-0036912 ┆ DeVonta    ┆ WR       ┆ PHI  ┆ … ┆ 78.333333  ┆ 0.0        ┆ 0          ┆ 1         │
│            ┆ Smith      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037240 ┆ Jameson    ┆ WR       ┆ DET  ┆ … ┆ 57.25      ┆ 0.0        ┆ 0          ┆ 0         │
│            ┆ Williams   ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [29]:
final_board = final_board.select([
    "gsis_id",
    "player",
    "position",
    "team",
    "opponent",
    "h_a",
    "gameday",
    "gametime",

    "games_played",
    "targets_per_game",
    "receptions_per_game",
    "receiving_yards_per_game",
    "rushing_yards_per_game",
    "rushing_tds",
    "receiving_tds",

    "pass_yards_allowed",
    "pass_tds_allowed",
    "rush_yards_allowed",
    "rush_tds_allowed"
])

final_board

shape: (13, 19)
┌────────────┬────────────┬──────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ gsis_id    ┆ player     ┆ position ┆ team ┆ … ┆ pass_yards ┆ pass_tds_a ┆ rush_yards ┆ rush_tds_ │
│ ---        ┆ ---        ┆ ---      ┆ ---  ┆   ┆ _allowed   ┆ llowed     ┆ _allowed   ┆ allowed   │
│ str        ┆ str        ┆ str      ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│            ┆            ┆          ┆      ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32       │
╞════════════╪════════════╪══════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 00-0041037 ┆ Denzel     ┆ WR       ┆ CLE  ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4         │
│            ┆ Boston     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0039165 ┆ Zach       ┆ RB       ┆ SEA  ┆ … ┆ 214.75     ┆ 4          ┆ 99.75      ┆ 2         │
│            ┆ Charbonnet ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038977 ┆ Tank Dell  ┆ WR       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│ 00-0039139 ┆ Jahmyr     ┆ RB       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Gibbs      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038120 ┆ Breece     ┆ RB       ┆ NYJ  ┆ … ┆ 254.25     ┆ 9          ┆ 113.25     ┆ 0         │
│            ┆ Hall       ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 00-0035685 ┆ David      ┆ RB       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│            ┆ Montgomery ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037239 ┆ Chris      ┆ WR       ┆ NO   ┆ … ┆ 220.25     ┆ 3          ┆ 94.5       ┆ 1         │
│            ┆ Olave      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0036970 ┆ Kyle Pitts ┆ TE       ┆ ATL  ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6         │
│ 00-0036912 ┆ DeVonta    ┆ WR       ┆ PHI  ┆ … ┆ 291.5      ┆ 3          ┆ 74.25      ┆ 2         │
│            ┆ Smith      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037240 ┆ Jameson    ┆ WR       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Williams   ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [30]:
final_board = final_board.rename({
    "targets_per_game": "tgt_pg",
    "receptions_per_game": "rec_pg",
    "receiving_yards_per_game": "rec_yds_pg",
    "rushing_yards_per_game": "rush_yds_pg",
    "rushing_tds": "rush_td",
    "receiving_tds": "rec_td",
    "pass_yards_allowed": "pass_yds_allowed",
    "pass_tds_allowed": "pass_td_allowed",
    "rush_yards_allowed": "rush_yds_allowed",
    "rush_tds_allowed": "rush_td_allowed"
})

In [31]:
final_board

shape: (13, 19)
┌────────────┬────────────┬──────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ gsis_id    ┆ player     ┆ position ┆ team ┆ … ┆ pass_yds_a ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_a │
│ ---        ┆ ---        ┆ ---      ┆ ---  ┆   ┆ llowed     ┆ lowed      ┆ llowed     ┆ llowed    │
│ str        ┆ str        ┆ str      ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│            ┆            ┆          ┆      ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32       │
╞════════════╪════════════╪══════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 00-0041037 ┆ Denzel     ┆ WR       ┆ CLE  ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4         │
│            ┆ Boston     ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0039165 ┆ Zach       ┆ RB       ┆ SEA  ┆ … ┆ 214.75     ┆ 4          ┆ 99.75      ┆ 2         │
│            ┆ Charbonnet ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038977 ┆ Tank Dell  ┆ WR       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│ 00-0039139 ┆ Jahmyr     ┆ RB       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Gibbs      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0038120 ┆ Breece     ┆ RB       ┆ NYJ  ┆ … ┆ 254.25     ┆ 9          ┆ 113.25     ┆ 0         │
│            ┆ Hall       ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ …          ┆ …          ┆ …        ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 00-0035685 ┆ David      ┆ RB       ┆ HOU  ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4         │
│            ┆ Montgomery ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037239 ┆ Chris      ┆ WR       ┆ NO   ┆ … ┆ 220.25     ┆ 3          ┆ 94.5       ┆ 1         │
│            ┆ Olave      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0036970 ┆ Kyle Pitts ┆ TE       ┆ ATL  ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6         │
│ 00-0036912 ┆ DeVonta    ┆ WR       ┆ PHI  ┆ … ┆ 291.5      ┆ 3          ┆ 74.25      ┆ 2         │
│            ┆ Smith      ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
│ 00-0037240 ┆ Jameson    ┆ WR       ┆ DET  ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3         │
│            ┆ Williams   ┆          ┆      ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────────┴──────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [32]:
matchup_board = final_board.select([
    "player",
    "position",
    "team",
    "opponent",
    "h_a",
    "gameday",
    "gametime",

    "pass_yds_allowed",
    "pass_td_allowed",
    "rush_yds_allowed",
    "rush_td_allowed"
])

matchup_board

shape: (13, 11)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_yds_a ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_al │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ lowed      ┆ llowed     ┆ lowed      │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4          │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 214.75     ┆ 4          ┆ 99.75      ┆ 2          │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4          │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3          │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 254.25     ┆ 9          ┆ 113.25     ┆ 0          │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.75     ┆ 4          │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 220.25     ┆ 3          ┆ 94.5       ┆ 1          │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6          │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 291.5      ┆ 3          ┆ 74.25      ┆ 2          │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 247.75     ┆ 11         ┆ 117.5      ┆ 3          │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [33]:
matchup_board = (
    matchup_board
    .join(
        defense_efficiency,
        left_on="opponent",
        right_on="defense_team",
        how="left"
    )
)

matchup_board

shape: (13, 14)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ rush_td_al ┆ rush_ypc_a ┆ net_pass_y ┆ yards_per_ │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ lowed      ┆ llowed     ┆ ds_per_dro ┆ play_allow │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ pback      ┆ ed         │
│             ┆          ┆      ┆          ┆   ┆ i32        ┆ f64        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆            ┆            ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 4          ┆ 4.26       ┆ 6.4        ┆ 5.42       │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 2          ┆ 3.73       ┆ 5.84       ┆ 4.97       │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 4          ┆ 3.66       ┆ 7.71       ┆ 5.57       │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 3          ┆ 4.2        ┆ 8.95       ┆ 6.62       │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 0          ┆ 4.58       ┆ 6.96       ┆ 6.04       │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 4          ┆ 3.66       ┆ 7.71       ┆ 5.57       │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 1          ┆ 4.15       ┆ 6.69       ┆ 5.72       │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 6          ┆ 3.88       ┆ 6.79       ┆ 5.57       │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 2          ┆ 3.26       ┆ 8.18       ┆ 6.31       │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 3          ┆ 4.2        ┆ 8.95       ┆ 6.62       │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [34]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("position") == "RB")
      .then(pl.col("rush_ypc_allowed"))
      .otherwise(pl.col("net_pass_yds_per_dropback"))
      .alias("key_efficiency_stat")
])

matchup_board

shape: (13, 15)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ rush_ypc_a ┆ net_pass_y ┆ yards_per_ ┆ key_effici │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ ds_per_dro ┆ play_allow ┆ ency_stat  │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ pback      ┆ ed         ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ ---        ┆ ---        ┆ f64        │
│             ┆          ┆      ┆          ┆   ┆            ┆ f64        ┆ f64        ┆            │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 4.26       ┆ 6.4        ┆ 5.42       ┆ 6.4        │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 3.73       ┆ 5.84       ┆ 4.97       ┆ 3.73       │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 3.66       ┆ 7.71       ┆ 5.57       ┆ 7.71       │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 4.2        ┆ 8.95       ┆ 6.62       ┆ 4.2        │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 4.58       ┆ 6.96       ┆ 6.04       ┆ 4.58       │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 3.66       ┆ 7.71       ┆ 5.57       ┆ 3.66       │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 4.15       ┆ 6.69       ┆ 5.72       ┆ 6.69       │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 3.88       ┆ 6.79       ┆ 5.57       ┆ 6.79       │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 3.26       ┆ 8.18       ┆ 6.31       ┆ 8.18       │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 4.2        ┆ 8.95       ┆ 6.62       ┆ 8.95       │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [35]:
player_details = final_board.select([
    "gsis_id",
    "player",
    "position",
    "team",
    "games_played",
    "tgt_pg",
    "rec_pg",
    "rec_yds_pg",
    "rush_yds_pg",
    "rush_td",
    "rec_td"
])

player_details

shape: (13, 11)
┌────────────┬─────────────────┬──────────┬──────┬───┬────────────┬─────────────┬─────────┬────────┐
│ gsis_id    ┆ player          ┆ position ┆ team ┆ … ┆ rec_yds_pg ┆ rush_yds_pg ┆ rush_td ┆ rec_td │
│ ---        ┆ ---             ┆ ---      ┆ ---  ┆   ┆ ---        ┆ ---         ┆ ---     ┆ ---    │
│ str        ┆ str             ┆ str      ┆ str  ┆   ┆ f64        ┆ f64         ┆ i32     ┆ i32    │
╞════════════╪═════════════════╪══════════╪══════╪═══╪════════════╪═════════════╪═════════╪════════╡
│ 00-0041037 ┆ Denzel Boston   ┆ WR       ┆ CLE  ┆ … ┆ 71.0       ┆ 0.0         ┆ 0       ┆ 2      │
│ 00-0039165 ┆ Zach Charbonnet ┆ RB       ┆ SEA  ┆ … ┆ null       ┆ null        ┆ null    ┆ null   │
│ 00-0038977 ┆ Tank Dell       ┆ WR       ┆ HOU  ┆ … ┆ null       ┆ null        ┆ null    ┆ null   │
│ 00-0039139 ┆ Jahmyr Gibbs    ┆ RB       ┆ DET  ┆ … ┆ 46.75      ┆ 88.25       ┆ 5       ┆ 2      │
│ 00-0038120 ┆ Breece Hall     ┆ RB       ┆ NYJ  ┆ … ┆ 34.0       ┆ 54.333333   ┆ 1       ┆ 0      │
│ …          ┆ …               ┆ …        ┆ …    ┆ … ┆ …          ┆ …           ┆ …       ┆ …      │
│ 00-0035685 ┆ David           ┆ RB       ┆ HOU  ┆ … ┆ 16.75      ┆ 31.75       ┆ 2       ┆ 1      │
│            ┆ Montgomery      ┆          ┆      ┆   ┆            ┆             ┆         ┆        │
│ 00-0037239 ┆ Chris Olave     ┆ WR       ┆ NO   ┆ … ┆ 122.75     ┆ 0.0         ┆ 0       ┆ 1      │
│ 00-0036970 ┆ Kyle Pitts      ┆ TE       ┆ ATL  ┆ … ┆ 16.75      ┆ 0.0         ┆ 0       ┆ 0      │
│ 00-0036912 ┆ DeVonta Smith   ┆ WR       ┆ PHI  ┆ … ┆ 78.333333  ┆ 0.0         ┆ 0       ┆ 1      │
│ 00-0037240 ┆ Jameson         ┆ WR       ┆ DET  ┆ … ┆ 57.25      ┆ 0.0         ┆ 0       ┆ 0      │
│            ┆ Williams        ┆          ┆      ┆   ┆            ┆             ┆         ┆        │
└────────────┴─────────────────┴──────────┴──────┴───┴────────────┴─────────────┴─────────┴────────┘

In [36]:
matchup_board = matchup_board.with_columns([
    pl.col("pass_yds_allowed").round(1),
    pl.col("rush_yds_allowed").round(1)
])

player_details = player_details.with_columns([
    pl.col("tgt_pg").round(1),
    pl.col("rec_pg").round(1),
    pl.col("rec_yds_pg").round(1),
    pl.col("rush_yds_pg").round(1)
])

In [37]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("position") == "RB")
      .then(pl.lit("Rush Defense"))
      .otherwise(pl.lit("Pass Defense"))
      .alias("matchup_focus"),

    pl.when(pl.col("position") == "RB")
      .then(pl.col("rush_yds_allowed"))
      .otherwise(pl.col("pass_yds_allowed"))
      .alias("key_def_stat")
])

In [38]:
matchup_board = matchup_board.select([
    "player",
    "position",
    "team",
    "opponent",
    "h_a",
    "gameday",
    "gametime",
    "matchup_focus",
    "key_def_stat",
    "pass_yds_allowed",
    "pass_td_allowed",
    "rush_yds_allowed",
    "rush_td_allowed"
])

matchup_board

shape: (13, 13)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_yds_a ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_al │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ lowed      ┆ llowed     ┆ lowed      │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4          │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 214.8      ┆ 4          ┆ 99.8       ┆ 2          │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 254.2      ┆ 9          ┆ 113.2      ┆ 0          │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 220.2      ┆ 3          ┆ 94.5       ┆ 1          │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6          │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 291.5      ┆ 3          ┆ 74.2       ┆ 2          │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [39]:
matchup_board = matchup_board.rename({
    "key_def_stat": "key_matchup_value"
})

In [40]:
matchup_board

shape: (13, 13)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_yds_a ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_al │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ lowed      ┆ llowed     ┆ lowed      │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4          │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 214.8      ┆ 4          ┆ 99.8       ┆ 2          │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 254.2      ┆ 9          ┆ 113.2      ┆ 0          │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 220.2      ┆ 3          ┆ 94.5       ┆ 1          │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6          │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 291.5      ┆ 3          ┆ 74.2       ┆ 2          │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [41]:
for col in team_stats.columns:
    if col in [
        "attempts",
        "carries",
        "sacks_suffered"
    ]:
        print(col)

attempts
sacks_suffered
carries

In [42]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("opponent") == "BYE")
      .then(pl.lit("BYE"))
      .otherwise(pl.col("matchup_focus"))
      .alias("matchup_focus")
])

matchup_board

shape: (13, 13)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_yds_a ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_al │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ lowed      ┆ llowed     ┆ lowed      │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ i32        ┆ f64        ┆ i32        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 205.5      ┆ 5          ┆ 123.5      ┆ 4          │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 214.8      ┆ 4          ┆ 99.8       ┆ 2          │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 254.2      ┆ 9          ┆ 113.2      ┆ 0          │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 220.5      ┆ 4          ┆ 122.8      ┆ 4          │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 220.2      ┆ 3          ┆ 94.5       ┆ 1          │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 229.0      ┆ 4          ┆ 100.0      ┆ 6          │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 291.5      ┆ 3          ┆ 74.2       ┆ 2          │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 247.8      ┆ 11         ┆ 117.5      ┆ 3          │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [43]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("opponent") == "BYE")
      .then(pl.lit("BYE WEEK"))
      .otherwise(pl.lit("ACTIVE"))
      .alias("week_status")
])

matchup_board

shape: (13, 14)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_td_al ┆ rush_yds_a ┆ rush_td_al ┆ week_statu │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ lowed      ┆ llowed     ┆ lowed      ┆ s          │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ i32        ┆ f64        ┆ i32        ┆ str        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 5          ┆ 123.5      ┆ 4          ┆ ACTIVE     │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 4          ┆ 99.8       ┆ 2          ┆ ACTIVE     │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 4          ┆ 122.8      ┆ 4          ┆ ACTIVE     │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 11         ┆ 117.5      ┆ 3          ┆ ACTIVE     │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 9          ┆ 113.2      ┆ 0          ┆ ACTIVE     │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 4          ┆ 122.8      ┆ 4          ┆ ACTIVE     │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 3          ┆ 94.5       ┆ 1          ┆ ACTIVE     │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 4          ┆ 100.0      ┆ 6          ┆ ACTIVE     │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 3          ┆ 74.2       ┆ 2          ┆ ACTIVE     │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 11         ┆ 117.5      ┆ 3          ┆ ACTIVE     │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [44]:
league_efficiency = defense_efficiency.select([
    pl.col("rush_ypc_allowed").mean().alias("league_rush_ypc"),
    pl.col("net_pass_yds_per_dropback").mean().alias("league_net_pass_ypd"),
    pl.col("yards_per_play_allowed").mean().alias("league_ypp")
])

league_efficiency

shape: (1, 3)
┌─────────────────┬─────────────────────┬────────────┐
│ league_rush_ypc ┆ league_net_pass_ypd ┆ league_ypp │
│ ---             ┆ ---                 ┆ ---        │
│ f64             ┆ f64                 ┆ f64        │
╞═════════════════╪═════════════════════╪════════════╡
│ 4.1584375       ┆ 7.092187            ┆ 5.820312   │
└─────────────────┴─────────────────────┴────────────┘

In [45]:
LEAGUE_RUSH_YPC = league_efficiency["league_rush_ypc"][0]
LEAGUE_NET_PASS_YPD = league_efficiency["league_net_pass_ypd"][0]
LEAGUE_YPP = league_efficiency["league_ypp"][0]

print("League Rush YPC:", round(LEAGUE_RUSH_YPC, 2))
print("League Net Pass Yds/Dropback:", round(LEAGUE_NET_PASS_YPD, 2))
print("League Yards/Play:", round(LEAGUE_YPP, 2))

League Rush YPC: 4.16
League Net Pass Yds/Dropback: 7.09
League Yards/Play: 5.82

In [46]:
defense_ranks = (
    defense_efficiency
    .with_columns([
        pl.col("rush_ypc_allowed")
          .rank("ordinal")
          .alias("rush_def_rank"),

        pl.col("net_pass_yds_per_dropback")
          .rank("ordinal")
          .alias("pass_def_rank")
    ])
    .select([
        "defense_team",
        "rush_def_rank",
        "pass_def_rank"
    ])
)

defense_ranks

shape: (32, 3)
┌──────────────┬───────────────┬───────────────┐
│ defense_team ┆ rush_def_rank ┆ pass_def_rank │
│ ---          ┆ ---           ┆ ---           │
│ str          ┆ u32           ┆ u32           │
╞══════════════╪═══════════════╪═══════════════╡
│ NYG          ┆ 25            ┆ 6             │
│ NO           ┆ 30            ┆ 19            │
│ NYJ          ┆ 19            ┆ 7             │
│ BAL          ┆ 11            ┆ 12            │
│ BUF          ┆ 14            ┆ 18            │
│ …            ┆ …             ┆ …             │
│ SF           ┆ 9             ┆ 3             │
│ PIT          ┆ 20            ┆ 26            │
│ PHI          ┆ 15            ┆ 8             │
│ ATL          ┆ 1             ┆ 5             │
│ CHI          ┆ 29            ┆ 23            │
└──────────────┴───────────────┴───────────────┘

In [47]:
matchup_board = (
    matchup_board
    .join(
        defense_ranks,
        left_on="opponent",
        right_on="defense_team",
        how="left"
    )
)

In [48]:
matchup_board = (
    matchup_board
    .join(
        defense_efficiency,
        left_on="opponent",
        right_on="defense_team",
        how="left"
    )
)

matchup_board

shape: (13, 19)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ pass_def_r ┆ rush_ypc_a ┆ net_pass_y ┆ yards_per_ │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ ank        ┆ llowed     ┆ ds_per_dro ┆ play_allow │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ pback      ┆ ed         │
│             ┆          ┆      ┆          ┆   ┆ u32        ┆ f64        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆            ┆            ┆ f64        ┆ f64        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 7          ┆ 4.26       ┆ 6.4        ┆ 5.42       │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 3          ┆ 3.73       ┆ 5.84       ┆ 4.97       │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 24         ┆ 3.66       ┆ 7.71       ┆ 5.57       │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 32         ┆ 4.2        ┆ 8.95       ┆ 6.62       │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 16         ┆ 4.58       ┆ 6.96       ┆ 6.04       │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 24         ┆ 3.66       ┆ 7.71       ┆ 5.57       │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 10         ┆ 4.15       ┆ 6.69       ┆ 5.72       │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 12         ┆ 3.88       ┆ 6.79       ┆ 5.57       │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 29         ┆ 3.26       ┆ 8.18       ┆ 6.31       │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 32         ┆ 4.2        ┆ 8.95       ┆ 6.62       │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [49]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("position") == "RB")
      .then(pl.col("rush_ypc_allowed") - LEAGUE_RUSH_YPC)
      .otherwise(
          pl.col("net_pass_yds_per_dropback") - LEAGUE_NET_PASS_YPD
      )
      .round(2)
      .alias("efficiency_vs_league")
])

matchup_board

shape: (13, 20)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ rush_ypc_a ┆ net_pass_y ┆ yards_per_ ┆ efficiency │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ llowed     ┆ ds_per_dro ┆ play_allow ┆ _vs_league │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ pback      ┆ ed         ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ ---        ┆ ---        ┆ f64        │
│             ┆          ┆      ┆          ┆   ┆            ┆ f64        ┆ f64        ┆            │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 4.26       ┆ 6.4        ┆ 5.42       ┆ -0.69      │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 3.73       ┆ 5.84       ┆ 4.97       ┆ -0.43      │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 3.66       ┆ 7.71       ┆ 5.57       ┆ 0.62       │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 4.2        ┆ 8.95       ┆ 6.62       ┆ 0.04       │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 4.58       ┆ 6.96       ┆ 6.04       ┆ 0.42       │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 3.66       ┆ 7.71       ┆ 5.57       ┆ -0.5       │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 4.15       ┆ 6.69       ┆ 5.72       ┆ -0.4       │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 3.88       ┆ 6.79       ┆ 5.57       ┆ -0.3       │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 3.26       ┆ 8.18       ┆ 6.31       ┆ 1.09       │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 4.2        ┆ 8.95       ┆ 6.62       ┆ 1.86       │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [50]:
matchup_board = matchup_board.with_columns(
    pl.col("efficiency_vs_league")
    .map_elements(
        lambda x: f"{x:+.2f}" if x is not None else "BYE",
        return_dtype=pl.Utf8
    )
    .alias("efficiency_vs_league_display")
)

matchup_board

shape: (13, 21)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ net_pass_y ┆ yards_per_ ┆ efficiency ┆ efficiency │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ ds_per_dro ┆ play_allow ┆ _vs_league ┆ _vs_league │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ pback      ┆ ed         ┆ ---        ┆ _display   │
│             ┆          ┆      ┆          ┆   ┆ ---        ┆ ---        ┆ f64        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ f64        ┆            ┆ str        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 6.4        ┆ 5.42       ┆ -0.69      ┆ -0.69      │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 5.84       ┆ 4.97       ┆ -0.43      ┆ -0.43      │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 7.71       ┆ 5.57       ┆ 0.62       ┆ +0.62      │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 8.95       ┆ 6.62       ┆ 0.04       ┆ +0.04      │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 6.96       ┆ 6.04       ┆ 0.42       ┆ +0.42      │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 7.71       ┆ 5.57       ┆ -0.5       ┆ -0.50      │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 6.69       ┆ 5.72       ┆ -0.4       ┆ -0.40      │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 6.79       ┆ 5.57       ┆ -0.3       ┆ -0.30      │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 8.18       ┆ 6.31       ┆ 1.09       ┆ +1.09      │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 8.95       ┆ 6.62       ┆ 1.86       ┆ +1.86      │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [51]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("week_status") == "BYE WEEK")
      .then(pl.lit("BYE"))

      .when(pl.col("efficiency_vs_league") >= 0.50)
      .then(pl.lit("Favorable"))

      .when(pl.col("efficiency_vs_league") <= -0.50)
      .then(pl.lit("Tough"))

      .otherwise(pl.lit("Neutral"))
      .alias("matchup_label")
])

matchup_board

shape: (13, 22)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ yards_per_ ┆ efficiency ┆ efficiency ┆ matchup_la │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ play_allow ┆ _vs_league ┆ _vs_league ┆ bel        │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ed         ┆ ---        ┆ _display   ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ ---        ┆ f64        ┆ ---        ┆ str        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆            ┆ str        ┆            │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 5.42       ┆ -0.69      ┆ -0.69      ┆ Tough      │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 4.97       ┆ -0.43      ┆ -0.43      ┆ Neutral    │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 5.57       ┆ 0.62       ┆ +0.62      ┆ Favorable  │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 6.62       ┆ 0.04       ┆ +0.04      ┆ Neutral    │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 6.04       ┆ 0.42       ┆ +0.42      ┆ Neutral    │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 5.57       ┆ -0.5       ┆ -0.50      ┆ Tough      │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 5.72       ┆ -0.4       ┆ -0.40      ┆ Neutral    │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 5.57       ┆ -0.3       ┆ -0.30      ┆ Neutral    │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 6.31       ┆ 1.09       ┆ +1.09      ┆ Favorable  │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 6.62       ┆ 1.86       ┆ +1.86      ┆ Favorable  │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [52]:
matchup_board = matchup_board.with_columns([
    pl.when(pl.col("position") == "RB")
      .then(pl.col("rush_def_rank"))
      .otherwise(pl.col("pass_def_rank"))
      .alias("key_def_rank")
])

matchup_board

shape: (13, 23)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ efficiency ┆ efficiency ┆ matchup_la ┆ key_def_ra │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ _vs_league ┆ _vs_league ┆ bel        ┆ nk         │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ _display   ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ f64        ┆ ---        ┆ str        ┆ u32        │
│             ┆          ┆      ┆          ┆   ┆            ┆ str        ┆            ┆            │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ -0.69      ┆ -0.69      ┆ Tough      ┆ 7          │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ -0.43      ┆ -0.43      ┆ Neutral    ┆ 9          │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 0.62       ┆ +0.62      ┆ Favorable  ┆ 24         │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 0.04       ┆ +0.04      ┆ Neutral    ┆ 18         │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 0.42       ┆ +0.42      ┆ Neutral    ┆ 24         │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ -0.5       ┆ -0.50      ┆ Tough      ┆ 8          │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ -0.4       ┆ -0.40      ┆ Neutral    ┆ 10         │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ -0.3       ┆ -0.30      ┆ Neutral    ┆ 12         │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 1.09       ┆ +1.09      ┆ Favorable  ┆ 29         │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 1.86       ┆ +1.86      ┆ Favorable  ┆ 32         │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [54]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

/Users/dova/Desktop/ff_tool

In [55]:
from src.data import build_dashboard_data

matchup_board, player_details = build_dashboard_data()

In [56]:
matchup_board

shape: (13, 24)
┌─────────────┬──────────┬──────┬──────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ player      ┆ position ┆ team ┆ opponent ┆ … ┆ rush_def_r ┆ pass_def_r ┆ key_def_ra ┆ week_statu │
│ ---         ┆ ---      ┆ ---  ┆ ---      ┆   ┆ ank        ┆ ank        ┆ nk         ┆ s          │
│ str         ┆ str      ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│             ┆          ┆      ┆          ┆   ┆ u32        ┆ u32        ┆ u32        ┆ str        │
╞═════════════╪══════════╪══════╪══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ Denzel      ┆ WR       ┆ CLE  ┆ NYJ      ┆ … ┆ 19         ┆ 7          ┆ 7          ┆ ACTIVE     │
│ Boston      ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Zach        ┆ RB       ┆ SEA  ┆ SF       ┆ … ┆ 9          ┆ 3          ┆ 9          ┆ ACTIVE     │
│ Charbonnet  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Tank Dell   ┆ WR       ┆ HOU  ┆ TEN      ┆ … ┆ 8          ┆ 24         ┆ 24         ┆ ACTIVE     │
│ Jahmyr      ┆ RB       ┆ DET  ┆ ARI      ┆ … ┆ 18         ┆ 32         ┆ 18         ┆ ACTIVE     │
│ Gibbs       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Breece Hall ┆ RB       ┆ NYJ  ┆ CLE      ┆ … ┆ 24         ┆ 16         ┆ 24         ┆ ACTIVE     │
│ …           ┆ …        ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ David       ┆ RB       ┆ HOU  ┆ TEN      ┆ … ┆ 8          ┆ 24         ┆ 8          ┆ ACTIVE     │
│ Montgomery  ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Chris Olave ┆ WR       ┆ NO   ┆ MIN      ┆ … ┆ 16         ┆ 11         ┆ 11         ┆ ACTIVE     │
│ Kyle Pitts  ┆ TE       ┆ ATL  ┆ BAL      ┆ … ┆ 11         ┆ 12         ┆ 12         ┆ ACTIVE     │
│ DeVonta     ┆ WR       ┆ PHI  ┆ JAX      ┆ … ┆ 3          ┆ 29         ┆ 29         ┆ ACTIVE     │
│ Smith       ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
│ Jameson     ┆ WR       ┆ DET  ┆ ARI      ┆ … ┆ 18         ┆ 32         ┆ 32         ┆ ACTIVE     │
│ Williams    ┆          ┆      ┆          ┆   ┆            ┆            ┆            ┆            │
└─────────────┴──────────┴──────┴──────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [57]:
player_details

shape: (13, 11)
┌────────────┬─────────────────┬──────────┬──────┬───┬────────────┬─────────────┬─────────┬────────┐
│ gsis_id    ┆ player          ┆ position ┆ team ┆ … ┆ rec_yds_pg ┆ rush_yds_pg ┆ rush_td ┆ rec_td │
│ ---        ┆ ---             ┆ ---      ┆ ---  ┆   ┆ ---        ┆ ---         ┆ ---     ┆ ---    │
│ str        ┆ str             ┆ str      ┆ str  ┆   ┆ f64        ┆ f64         ┆ i32     ┆ i32    │
╞════════════╪═════════════════╪══════════╪══════╪═══╪════════════╪═════════════╪═════════╪════════╡
│ 00-0041037 ┆ Denzel Boston   ┆ WR       ┆ CLE  ┆ … ┆ 71.0       ┆ 0.0         ┆ 0       ┆ 2      │
│ 00-0039165 ┆ Zach Charbonnet ┆ RB       ┆ SEA  ┆ … ┆ null       ┆ null        ┆ null    ┆ null   │
│ 00-0038977 ┆ Tank Dell       ┆ WR       ┆ HOU  ┆ … ┆ null       ┆ null        ┆ null    ┆ null   │
│ 00-0039139 ┆ Jahmyr Gibbs    ┆ RB       ┆ DET  ┆ … ┆ 46.8       ┆ 88.2        ┆ 5       ┆ 2      │
│ 00-0038120 ┆ Breece Hall     ┆ RB       ┆ NYJ  ┆ … ┆ 34.0       ┆ 54.3        ┆ 1       ┆ 0      │
│ …          ┆ …               ┆ …        ┆ …    ┆ … ┆ …          ┆ …           ┆ …       ┆ …      │
│ 00-0035685 ┆ David           ┆ RB       ┆ HOU  ┆ … ┆ 16.8       ┆ 31.8        ┆ 2       ┆ 1      │
│            ┆ Montgomery      ┆          ┆      ┆   ┆            ┆             ┆         ┆        │
│ 00-0037239 ┆ Chris Olave     ┆ WR       ┆ NO   ┆ … ┆ 122.8      ┆ 0.0         ┆ 0       ┆ 1      │
│ 00-0036970 ┆ Kyle Pitts      ┆ TE       ┆ ATL  ┆ … ┆ 16.8       ┆ 0.0         ┆ 0       ┆ 0      │
│ 00-0036912 ┆ DeVonta Smith   ┆ WR       ┆ PHI  ┆ … ┆ 78.3       ┆ 0.0         ┆ 0       ┆ 1      │
│ 00-0037240 ┆ Jameson         ┆ WR       ┆ DET  ┆ … ┆ 57.2       ┆ 0.0         ┆ 0       ┆ 0      │
│            ┆ Williams        ┆          ┆      ┆   ┆            ┆             ┆         ┆        │
└────────────┴─────────────────┴──────────┴──────┴───┴────────────┴─────────────┴─────────┴────────┘